; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = teensy41

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
	majerle/LwGPS@^2.2.0
build_flags = 
	-Iinclude
	-I${PROJECT_LIBDEPS_DIR}/${PIOENV}/LwGPS/lwgps/src/include

[env:teensy41_microros]
platform = teensy
board = teensy41
framework = arduino
lib_deps =
	majerle/LwGPS@^2.2.0
	https://github.com/micro-ROS/micro_ros_platformio
board_microros_distro = humble
board_microros_transport = serial
build_flags =
	-DUSE_MICROROS=1
	-Iinclude
	-I${PROJECT_LIBDEPS_DIR}/${PIOENV}/LwGPS/lwgps/src/include
